"""Launcher script generation with auto-patching of .toe files."""

import os
import re

from .utils import TD_BASE_DIR, ensure_dir, info, success
from .wine import RUNNER_DIR, WINE_PREFIX

LAUNCHER_PATH = os.path.expanduser("~/.local/bin/launch-touchdesigner.sh")
BACKUP_DIR = os.path.join(TD_BASE_DIR, "backups")


def _get_existing_nvidia() -> str:
    """Read USE_NVIDIA_DGPU from existing launcher, return 'Y' or 'N'."""
    if os.path.isfile(LAUNCHER_PATH):
        try:
            with open(LAUNCHER_PATH) as f:
                for line in f:
                    m = re.match(r'^USE_NVIDIA_DGPU="?([YN])"?', line)
                    if m:
                        return m.group(1)
        except OSError:
            pass
    return ""


def create_launcher_script(nvidia_offload: bool = False) -> str:
    """Generate the launcher shell script and return its path.

    The launcher includes auto-patching of .toe files with wine_ui_fixes.tox,
    backup creation, and NVIDIA offload support.
    """
    ensure_dir(os.path.dirname(LAUNCHER_PATH))

    # Preserve existing NVIDIA setting if not explicitly changed
    nvidia_mode = ""
    if nvidia_offload:
        nvidia_mode = "Y"
    else:
        nvidia_mode = _get_existing_nvidia() or "N"

    launcher_content = f'''#!/bin/bash
# TouchDesigner launcher — generated by td-install
TD_BASE_DIR="${{TD_BASE_DIR:-${{HOME}}/.local/share/touchdesigner-linux}}"
RUNNER_DIR="${{TD_BASE_DIR%/}}/runner"
WINE_PREFIX="${{TD_BASE_DIR%/}}/prefix"
SOURCE_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
BACKUP_DIR="${{TD_BASE_DIR%/}}/backups"
USE_NVIDIA_DGPU="{nvidia_mode}"

export WAYLAND_DISPLAY=""
export __GL_YIELD="USLEEP"

find_touchdesigner_exe() {{
    find "$WINE_PREFIX/drive_c" -type f -iname 'TouchDesigner.exe' 2>/dev/null | sort -V | tail -n 1
}}

TOUCHDESIGNER_EXE_OVERRIDE_ARG=""
if [[ "$1" == "--exe" ]] && [ -n "$2" ]]; then
    TOUCHDESIGNER_EXE_OVERRIDE_ARG="$2"
    shift 2
elif [[ "$1" == --exe=* ]]; then
    TOUCHDESIGNER_EXE_OVERRIDE_ARG="${{1#--exe=}}"
    shift
fi

if [ -n "$TOUCHDESIGNER_EXE_OVERRIDE_ARG" ] && [ -f "$TOUCHDESIGNER_EXE_OVERRIDE_ARG" ]; then
    TOUCHDESIGNER_EXE="$TOUCHDESIGNER_EXE_OVERRIDE_ARG"
elif [ -n "$TOUCHDESIGNER_EXE_OVERRIDE" ] && [ -f "$TOUCHDESIGNER_EXE_OVERRIDE" ]; then
    TOUCHDESIGNER_EXE="$TOUCHDESIGNER_EXE_OVERRIDE"
else
    TOUCHDESIGNER_EXE="$(find_touchdesigner_exe)"
fi

if [ -z "$TOUCHDESIGNER_EXE" ]; then
    echo "Error: TouchDesigner.exe not found in Wine prefix."
    exit 1
fi

if command -v nvidia-smi >/dev/null 2>&1; then
    if [ "$USE_NVIDIA_DGPU" = "Y" ] || [ "$USE_NVIDIA_DGPU" = "y" ]; then
        export __NV_PRIME_RENDER_OFFLOAD=1
        export __GLX_VENDOR_LIBRARY_NAME=nvidia
        export __VK_LAYER_NV_optimus=NVIDIA_only
        export DRI_PRIME=1
    fi
fi

# Handle optional .toe file argument
EXTRA_ARGS=()
INPUT_PATH=""
if [ -n "$1" ]; then
    INPUT_PATH="$1"
    if [[ "$INPUT_PATH" == file://* ]]; then
        INPUT_PATH="${{INPUT_PATH#file://}}"
        INPUT_PATH="$(python3 -c "import sys, urllib.parse; print(urllib.parse.unquote(sys.argv[1]))" "$INPUT_PATH" 2>/dev/null || echo "$INPUT_PATH")"
    fi
    WINE_PATH="z:${{INPUT_PATH//\\/\\\\\\\\}}"
    EXTRA_ARGS=("$WINE_PATH")
fi

# ── Auto-patching .toe files with wine_ui_fixes.tox ─────────────────
TOE_EXPAND="$(find "$WINE_PREFIX/drive_c" -type f -iname 'toeexpand.exe' 2>/dev/null | head -n1 || true)"
TOE_COLLAPSE="$(find "$WINE_PREFIX/drive_c" -type f -iname 'toecollapse.exe' 2>/dev/null | head -n1 || true)"
FIX_FILE="$TD_BASE_DIR/wine_ui_fixes.tox"

check_and_patch_toe() {{
    local TOE_PATH="$1"
    [ -f "$TOE_PATH" ] || return 0
    local TOE_BASE TOE_DIR DIR_PATH TOC_PATH WINE_TOE
    TOE_BASE="$(basename "$TOE_PATH")"
    TOE_DIR="$(dirname "$TOE_PATH")"
    DIR_PATH="$TOE_DIR/${{TOE_BASE}}.dir"
    TOC_PATH="$TOE_DIR/${{TOE_BASE}}.toc"
    WINE_TOE="z:${{TOE_PATH//\\/\\\\\\\\}}"

    # Check if already patched
    rm -rf "$DIR_PATH" "$TOC_PATH" 2>/dev/null || true
    WINEPREFIX="$WINE_PREFIX" "$RUNNER_DIR/bin/wine64" "$TOE_EXPAND" "$WINE_TOE" >/dev/null 2>&1 || true
    local NEEDS_PATCH=false
    if [ ! -d "$DIR_PATH/wine_ui_fixes" ]; then
        NEEDS_PATCH=true
    fi
    rm -rf "$DIR_PATH" "$TOC_PATH" 2>/dev/null || true

    if [ "$NEEDS_PATCH" = true ]; then
        # Backup centralise (nom unique base sur le chemin complet)
        mkdir -p "$BACKUP_DIR" 2>/dev/null || true
        local UNIQUE_BAK_NAME="${{TOE_PATH//\\//_}}.bak"
        cp -f "$TOE_PATH" "$BACKUP_DIR/$UNIQUE_BAK_NAME" 2>/dev/null || true
        # Expand target .toe
        WINEPREFIX="$WINE_PREFIX" "$RUNNER_DIR/bin/wine64" "$TOE_EXPAND" "$WINE_TOE" >/dev/null 2>&1 || true
        if [ -d "$DIR_PATH" ]; then
            # Merge fix
            local MERGE_TMP="$(mktemp -d "/tmp/td_merge_toe.XXXXXX" 2>/dev/null || true)"
            if [ -n "$MERGE_TMP" ]; then
                local MERGE_FIX="$MERGE_TMP/fix.tox"
                cp -f "$FIX_FILE" "$MERGE_FIX" 2>/dev/null || true
                local WINE_MFIX="z:${{MERGE_FIX//\\/\\\\\\\\}}"
                WINEPREFIX="$WINE_PREFIX" "$RUNNER_DIR/bin/wine64" "$TOE_EXPAND" "$WINE_MFIX" >/dev/null 2>&1 || true
                if [ -d "$MERGE_FIX.dir" ]; then
                    cp -rf "$MERGE_FIX.dir/"* "$DIR_PATH/" 2>/dev/null || true
                fi
                rm -rf "$MERGE_TMP" 2>/dev/null || true
            fi
            # Add fix entries to .toc
            for entry in "${{FIX_ENTRIES[@]}}"; do
                echo "$entry" >> "$TOC_PATH"
            done
            WINEPREFIX="$WINE_PREFIX" "$RUNNER_DIR/bin/wine64" "$TOE_COLLAPSE" "$WINE_TOE" >/dev/null 2>&1 || true
        fi
        rm -rf "$DIR_PATH" "$TOC_PATH" 2>/dev/null || true
    fi
}}

if [ -n "$TOE_EXPAND" ] && [ -n "$TOE_COLLAPSE" ] && [ -f "$FIX_FILE" ]; then
    # Read fix .toc entries once (shared across all patches)
    FIX_TMPDIR="$(mktemp -d "/tmp/td_fix_launcher.XXXXXX" 2>/dev/null || true)"
    if [ -n "$FIX_TMPDIR" ]; then
        FIX_COPY="$FIX_TMPDIR/fix.tox"
        cp -f "$FIX_FILE" "$FIX_COPY" 2>/dev/null || true
        WINE_FIX_COPY="z:${{FIX_COPY//\\/\\\\\\\\}}"
        WINEPREFIX="$WINE_PREFIX" "$RUNNER_DIR/bin/wine64" "$TOE_EXPAND" "$WINE_FIX_COPY" >/dev/null 2>&1 || true

        if [ -d "$FIX_COPY.dir" ]; then
            # Read fix entries
            FIX_ENTRIES=()
            while IFS= read -r entry; do
                [ -z "$entry" ] && continue
                [[ "$entry" == \\#* ]] && continue
                [ "$entry" = ".build" ] && continue
                FIX_ENTRIES+=("$entry")
            done < "$FIX_COPY.toc"

            # Patch NewProject.toe files in drive_c (TD default templates)
            while IFS= read -r -d '' NP_TOE; do
                check_and_patch_toe "$NP_TOE"
            done < <(find "$WINE_PREFIX/drive_c" -type f -iname 'NewProject.toe' -print0 2>/dev/null || true)

            # Patch custom template from pref.txt if set
            PREF_FILE="$WINE_PREFIX/drive_c/users/steamuser/AppData/Local/Derivative/TouchDesigner099/pref.txt"
            if [ -f "$PREF_FILE" ]; then
                STARTUP_MODE=$(grep -E '^general\\.startupfilemode' "$PREF_FILE" 2>/dev/null | head -n1 | cut -f2 | tr -d '\\r' || true)
                if [ "$STARTUP_MODE" = "2" ]; then
                    CUSTOM_TOE=$(grep -E '^general\\.startupfilename' "$PREF_FILE" 2>/dev/null | head -n1 | cut -f2- | tr -d '\\r' || true)
                    if [ -n "$CUSTOM_TOE" ]; then
                        PATCH_CUSTOM_TOE="${{CUSTOM_TOE#z:}}"
                        PATCH_CUSTOM_TOE="${{PATCH_CUSTOM_TOE#Z:}}"
                        PATCH_CUSTOM_TOE="${{PATCH_CUSTOM_TOE//\\\\\\\\//}}"
                        [ -f "$PATCH_CUSTOM_TOE" ] && check_and_patch_toe "$PATCH_CUSTOM_TOE"
                    fi
                fi
            fi

            # Patch the .toe file passed as argument (double-click or CLI)
            if [ -n "$INPUT_PATH" ] && [[ "$INPUT_PATH" == *.toe ]]; then
                check_and_patch_toe "$INPUT_PATH"
            fi
        fi
        rm -rf "$FIX_TMPDIR" 2>/dev/null || true
    fi
fi

# ── First-launch setup: wineboot, license, DPI ────────────────────
INIT_FLAG="$WINE_PREFIX/.td_initialized"

if [ ! -f "$INIT_FLAG" ] && [ -f "$RUNNER_DIR/bin/wineboot" ]; then
echo "TouchDesigner - Setting up..."

# Backup license before wineboot
if [ -d "$WINE_PREFIX/drive_c/ProgramData/Derivative" ]; then
    rm -rf "$WINE_PREFIX/drive_c/ProgramData/Derivative.bak" 2>/dev/null || true
    cp -r "$WINE_PREFIX/drive_c/ProgramData/Derivative" \
          "$WINE_PREFIX/drive_c/ProgramData/Derivative.bak" 2>/dev/null || true
fi

# Initialize prefix
WINEPREFIX="$WINE_PREFIX" "$RUNNER_DIR/bin/wineboot" -u >/dev/null 2>&1 || true
sleep 2

# Restore license after wineboot
if [ -d "$WINE_PREFIX/drive_c/ProgramData/Derivative.bak" ]; then
    rm -rf "$WINE_PREFIX/drive_c/ProgramData/Derivative" 2>/dev/null || true
    cp -r "$WINE_PREFIX/drive_c/ProgramData/Derivative.bak" \
          "$WINE_PREFIX/drive_c/ProgramData/Derivative" 2>/dev/null || true
    rm -rf "$WINE_PREFIX/drive_c/ProgramData/Derivative.bak" 2>/dev/null || true
fi

# Auto-detect and apply DPI from Xft.dpi
XFT_DPI=$(xrdb -query 2>/dev/null | grep "^Xft.dpi" | awk '{{print $2}}' | head -1)
if [ -z "$XFT_DPI" ]; then
    XFT_DPI=$(xdpyinfo 2>/dev/null | grep "resolution" | grep -oP '[0-9]+(?=x)' | head -1)
fi
XFT_DPI=${{XFT_DPI:-96}}

if [ "$XFT_DPI" -lt 108 ]; then
    LOGPX=96
elif [ "$XFT_DPI" -lt 132 ]; then
    LOGPX=120
elif [ "$XFT_DPI" -lt 168 ]; then
    LOGPX=144
else
    LOGPX=192
fi

WINEPREFIX="$WINE_PREFIX" "$RUNNER_DIR/bin/wine64" reg add \
    "HKEY_CURRENT_CONFIG\\\\Software\\\\Fonts" \
    /v LogPixels /t REG_DWORD /d $LOGPX /f >/dev/null 2>&1 || true

touch "$INIT_FLAG"
elif [ -n "${{TD_DPI:-}}" ]; then
# Apply DPI override on any launch
WINEPREFIX="$WINE_PREFIX" "$RUNNER_DIR/bin/wine64" reg add \
    "HKEY_CURRENT_CONFIG\\\\Software\\\\Fonts" \
    /v LogPixels /t REG_DWORD /d "${{TD_DPI}}" /f >/dev/null 2>&1 || true
fi

# Auto-cleanup backups older than 30 days
if [ -d "$BACKUP_DIR" ]; then
    find "$BACKUP_DIR" -name '*.bak' -type f -mtime +30 -delete 2>/dev/null || true
fi

# Launch
PATH="$RUNNER_DIR/bin:$PATH"
export WINEPREFIX="$WINE_PREFIX"
exec "$RUNNER_DIR/bin/wine64" "$TOUCHDESIGNER_EXE" "${{EXTRA_ARGS[@]}}"
'''

    with open(LAUNCHER_PATH, "w") as f:
        f.write(launcher_content)

    os.chmod(LAUNCHER_PATH, 0o755)
    success(f"Launcher created: {LAUNCHER_PATH}")
    return LAUNCHER_PATH
