"""Launcher script generation with auto-patching of .toe files."""

import os

from . import __version__
from .utils import TD_BASE_DIR, ensure_dir, info, success, warning
from .wine import RUNNER_DIR, WINE_PREFIX

LAUNCHER_PATH = os.path.expanduser("~/.local/bin/launch-touchdesigner.sh")
# Friendly terminal command, symlinked to the launcher (the AUR package
# already ships /usr/bin/touchdesigner — parity for curl installs).
TD_COMMAND = os.path.expanduser("~/.local/bin/touchdesigner")
BACKUP_DIR = os.path.join(TD_BASE_DIR, "backups")


def create_launcher_script() -> str:
    """Generate the launcher shell script and return its path.

    The launcher includes auto-patching of .toe files with wine_ui_fixes.tox
    and backup creation. No GPU offloading is forced — the system default
    usage. On hybrid laptops, NVIDIA is auto-detected and used if available.
    """
    ensure_dir(os.path.dirname(LAUNCHER_PATH))

    # ── Distrobox container mode ──
    # When the install lives inside a container, the launcher must re-enter
    # it when invoked from the host (desktop shortcut, .toe association,
    # terminal). DISTROBOX_ENTER_PATH is only set once we are inside, which
    # makes the re-exec idempotent.
    from .container import CONTAINER_NAME, is_container_mode

    container_mode = is_container_mode()
    container_shim = ""
    if container_mode:
        container_shim = f'''
# ── Distrobox container mode ─────────────────────────────────────────────
# This install runs inside a distrobox container. When launched from the
# host, re-enter the container first.
if [ -z "${{DISTROBOX_ENTER_PATH:-}}" ] && command -v distrobox >/dev/null 2>&1; then
    exec distrobox enter "${{TD_CONTAINER_NAME:-{CONTAINER_NAME}}}" -- "$0" "$@"
fi
'''

    # A non-default TD_BASE_DIR (e.g. to escape a noexec $HOME) lives inside
    # the container, so it must be baked in — desktop shortcuts launch the
    # launcher from the host without that env var.
    baked_base = ""
    if container_mode and TD_BASE_DIR != os.path.expanduser(
        "~/.local/share/touchdesigner-linux"
    ):
        baked_base = f'export TD_BASE_DIR="{TD_BASE_DIR}"\n'

    # ── Template: note that {{ and }} escape literal braces in the f-string ──
    launcher_content = f'''#!/bin/bash
# TouchDesigner launcher --- generated by td-install
{baked_base}TD_BASE_DIR="${{TD_BASE_DIR:-${{HOME}}/.local/share/touchdesigner-linux}}"
RUNNER_DIR="${{TD_BASE_DIR%/}}/runner"
WINE_PREFIX="${{TD_BASE_DIR%/}}/prefix"
# ── CLI: flags are parsed before anything else; -h/-v/--list answer
# without launching TD, unknown flags are rejected instead of being
# treated as a .toe path ──
NO_PATCH=""
while true; do
    case "$1" in
      -h|--help)
        cat <<'HELP'
Usage: touchdesigner [options] [project.toe]

Launch TouchDesigner (Wine). Works from the host and from inside the
'touchdesigner-linux' distrobox container.

Options:
  -h, --help        Show this help and exit
  -v, --version     Tool version + installed TouchDesigner versions
  --list            Tool version + versions with full paths
  --no-patch        Skip the automatic .toe font-fix patching
  --verbose         Show Wine debug output (errors and warnings)
  --exe <path>      Launch a specific TouchDesigner.exe (or --exe=<path>)
  project.toe       Open a project file (file:// URLs work too)

Run 'td-install --diagnose' for a full system health check.
HELP
        exit 0
        ;;
      -v|--version|--list)
        echo "TouchDesigner-Linux v{__version__}"
        FOUND="$(find "$WINE_PREFIX/drive_c" -type f -iname 'TouchDesigner.exe' 2>/dev/null | sort -V)"
        if [ -z "$FOUND" ]; then
            echo "TouchDesigner: not installed in $WINE_PREFIX" >&2
            exit 1
        fi
        echo "Installed TouchDesigner versions:"
        printf '%s\n' "$FOUND" | while IFS= read -r exe; do
            ver="$(printf '%s' "$exe" | grep -oE '[0-9]{{4}}\\.[0-9]+' | head -n1)"
            if [ "$1" = "--list" ]; then
                printf '  %-12s %s\n' "${{ver:-unknown}}" "$exe"
            elif [ -n "$ver" ]; then
                echo "  $ver"
            else
                echo "  $exe"
            fi
        done
        exit 0
        ;;
      --no-patch)
        NO_PATCH=1
        shift
        ;;
      --verbose)
        export WINEDEBUG="${{WINEDEBUG:-err+all,warn+all}}"
        shift
        ;;
      --exe|--exe=*)
        break # handled further down
        ;;
      -*)
        echo "touchdesigner: unknown option: $1" >&2
        echo "Run 'touchdesigner --help' for usage." >&2
        exit 2
        ;;
      *)
        break
        ;;
    esac
done
{container_shim}
SOURCE_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
BACKUP_DIR="${{TD_BASE_DIR%/}}/backups"
LOG_FILE="${{TD_BASE_DIR%/}}/logs/launcher.log"

# --- Logging: most users launch via desktop icon (Terminal=false), so a
# bare `echo` on failure is invisible. Log to a file and, best-effort,
# raise a desktop notification so a silent icon click isn't a dead end. ---
log() {{
    mkdir -p "${{TD_BASE_DIR%/}}/logs" 2>/dev/null || true
    echo "[$(date '+%F %T')] $*" >> "$LOG_FILE" 2>/dev/null || true
}}
notify_fail() {{
    log "ERROR: $*"
    echo "Error: $*" >&2
    command -v notify-send >/dev/null 2>&1 && notify-send -a "TouchDesigner" -u critical -i "TouchDesigner" "TouchDesigner failed to start" "$*" 2>/dev/null || true
}}
notify_warn() {{
    log "WARN: $*"
    echo "  !! $*" >&2
    command -v notify-send >/dev/null 2>&1 && notify-send -a "TouchDesigner" -u normal -i "TouchDesigner" "TouchDesigner" "$*" 2>/dev/null || true
}}

# --- Find wine64 (support both Soda runner and AUR paths) ---
find_wine64() {{
    if [ -f "$RUNNER_DIR/bin/wine64" ]; then
        echo "$RUNNER_DIR/bin/wine64"
        return 0
    fi
    if [ -f "/opt/touchdesigner/wine/bin/wine64" ]; then
        echo "/opt/touchdesigner/wine/bin/wine64"
        return 0
    fi
    command -v wine64 2>/dev/null || echo ""
}}
WINE64_BIN="$(find_wine64)"

if [ -z "$WINE64_BIN" ]; then
    notify_fail "wine64 not found. Is TouchDesigner installed?"
    exit 1
fi
WINE_BIN="$(dirname "$WINE64_BIN")"

export WAYLAND_DISPLAY=""
export __GL_YIELD="USLEEP"
export KMP_AFFINITY="disabled"  # Fixes Intel OpenMP (torch) under Wine TkG
export PYTHONPATH="${{PYTHONPATH:+${{PYTHONPATH}}:}}C:/users/steamuser/AppData/Roaming/Python/Python311/site-packages"

find_touchdesigner_exe() {{
    local exe
    exe=$(find "$WINE_PREFIX/drive_c" -type f -iname 'TouchDesigner.exe' 2>/dev/null | sort -V | tail -n 1)
    if [ -n "$exe" ]; then
        echo "$exe"
        return 0
    fi
    if [ -f "/opt/touchdesigner/td/bin/TouchDesigner.exe" ]; then
        echo "/opt/touchdesigner/td/bin/TouchDesigner.exe"
        return 0
    fi
    find /opt/touchdesigner -type f -iname 'TouchDesigner.exe' 2>/dev/null | head -n 1
}}

TOUCHDESIGNER_EXE_OVERRIDE_ARG=""
if [[ "$1" == "--exe" ]] && [ -n "$2" ]; then
    TOUCHDESIGNER_EXE_OVERRIDE_ARG="$2"
    shift 2
elif [[ "$1" == --exe=* ]]; then
    TOUCHDESIGNER_EXE_OVERRIDE_ARG="${{1#--exe=}}"
    shift
fi

if [ -n "$TOUCHDESIGNER_EXE_OVERRIDE_ARG" ] && [ -f "$TOUCHDESIGNER_EXE_OVERRIDE_ARG" ]; then
    TOUCHDESIGNER_EXE="$TOUCHDESIGNER_EXE_OVERRIDE_ARG"
elif [ -n "$TOUCHDESIGNER_EXE_OVERRIDE" ] && [ -f "$TOUCHDESIGNER_EXE_OVERRIDE" ]; then
    TOUCHDESIGNER_EXE="$TOUCHDESIGNER_EXE_OVERRIDE"
else
    TOUCHDESIGNER_EXE="$(find_touchdesigner_exe)"
fi

if [ -z "$TOUCHDESIGNER_EXE" ]; then
    notify_fail "TouchDesigner.exe not found in Wine prefix."
    exit 1
fi

# Auto-detect NVIDIA dGPU on hybrid laptops — only when the driver actually
# works. nvidia-smi can exist while the driver fails (e.g. GPU passthrough or a
# missing kernel module); forcing the offload vars then breaks GLX and
# TouchDesigner refuses to start.
if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
    export __NV_PRIME_RENDER_OFFLOAD=1
    export __GLX_VENDOR_LIBRARY_NAME=nvidia
    export DRI_PRIME=1
fi

# Handle optional .toe file argument
EXTRA_ARGS=()
INPUT_PATH=""
if [ -n "$1" ]; then
    INPUT_PATH="$1"
    if [[ "$INPUT_PATH" == file://* ]]; then
        INPUT_PATH="${{INPUT_PATH#file://}}"
        INPUT_PATH="$(python3 -c "import sys, urllib.parse; print(urllib.parse.unquote(sys.argv[1]))" "$INPUT_PATH" 2>/dev/null || echo "$INPUT_PATH")"
    fi
    WINE_PATH="z:${{INPUT_PATH//\\/\\\\\\\\}}"
    EXTRA_ARGS=("$WINE_PATH")
fi

# --- Auto-patching .toe files with wine_ui_fixes.tox ---
TOE_EXPAND="$(find "$WINE_PREFIX/drive_c" -type f -iname 'toeexpand.exe' 2>/dev/null | head -n1 || true)"
[ -n "$TOE_EXPAND" ] || TOE_EXPAND="/opt/touchdesigner/td/bin/toeexpand.exe"
TOE_COLLAPSE="$(find "$WINE_PREFIX/drive_c" -type f -iname 'toecollapse.exe' 2>/dev/null | head -n1 || true)"
[ -n "$TOE_COLLAPSE" ] || TOE_COLLAPSE="/opt/touchdesigner/td/bin/toecollapse.exe"
FIX_FILE="$TD_BASE_DIR/wine_ui_fixes.tox"

# Content fingerprint of an expanded TD folder's logic (DAT scripts only:
# .text/.table files, which survive the round-trip unchanged; node metadata
# .n/.parm can legitimately differ after a project save).
fp_tree() {{
    local ROOT="$1"
    [ -d "$ROOT" ] || {{ echo "MISSING"; return; }}
    ( cd "$ROOT" 2>/dev/null && find . -type f \\( -name '*.text' -o -name '*.table' \\) -print0 2>/dev/null | sort -z | xargs -0 md5sum 2>/dev/null | md5sum 2>/dev/null ) || echo "MISSING"
}}

check_and_patch_toe() {{
    local TOE_PATH="$1"
    [ -f "$TOE_PATH" ] || return 0
    local TOE_BASE TOE_DIR DIR_PATH TOC_PATH WINE_TOE
    TOE_BASE="$(basename "$TOE_PATH")"
    TOE_DIR="$(dirname "$TOE_PATH")"
    DIR_PATH="$TOE_DIR/${{TOE_BASE}}.dir"
    TOC_PATH="$TOE_DIR/${{TOE_BASE}}.toc"
    WINE_TOE="z:${{TOE_PATH//\\/\\\\\\\\}}"

    rm -rf "$DIR_PATH" "$TOC_PATH" 2>/dev/null || true
    WINEPREFIX="$WINE_PREFIX" "$WINE64_BIN" "$TOE_EXPAND" "$WINE_TOE" >/dev/null 2>&1 || true
    local NEEDS_PATCH=false
    if [ -n "$FIX_FP" ]; then
        # Version-aware: repatch if the injected fix differs from the current one
        local INJECTED_FP="MISSING"
        [ -d "$DIR_PATH/wine_ui_fixes" ] && INJECTED_FP="$(fp_tree "$DIR_PATH/wine_ui_fixes")"
        [ "$INJECTED_FP" != "$FIX_FP" ] && NEEDS_PATCH=true
    elif [ ! -d "$DIR_PATH/wine_ui_fixes" ]; then
        NEEDS_PATCH=true
    fi
    rm -rf "$DIR_PATH" "$TOC_PATH" 2>/dev/null || true

    if [ "$NEEDS_PATCH" = true ]; then
        mkdir -p "$BACKUP_DIR" 2>/dev/null || true
        local UNIQUE_BAK_NAME="${{TOE_PATH//\\//_}}.bak"
        cp -f "$TOE_PATH" "$BACKUP_DIR/$UNIQUE_BAK_NAME" 2>/dev/null || true
        WINEPREFIX="$WINE_PREFIX" "$WINE64_BIN" "$TOE_EXPAND" "$WINE_TOE" >/dev/null 2>&1 || true
        if [ -d "$DIR_PATH" ]; then
            local MERGE_TMP="$(mktemp -d "/tmp/td_merge_toe.XXXXXX" 2>/dev/null || true)"
            if [ -n "$MERGE_TMP" ]; then
                local MERGE_FIX="$MERGE_TMP/fix.tox"
                cp -f "$FIX_FILE" "$MERGE_FIX" 2>/dev/null || true
                local WINE_MFIX="z:${{MERGE_FIX//\\/\\\\\\\\}}"
                WINEPREFIX="$WINE_PREFIX" "$WINE64_BIN" "$TOE_EXPAND" "$WINE_MFIX" >/dev/null 2>&1 || true
                if [ -d "$MERGE_FIX.dir" ]; then
                    rm -rf "$DIR_PATH/wine_ui_fixes" 2>/dev/null || true
                    cp -rf "$MERGE_FIX.dir/"* "$DIR_PATH/" 2>/dev/null || true
                fi
                rm -rf "$MERGE_TMP" 2>/dev/null || true
            fi
            # Replace stale fix entries from a previous injection, then add the
            # current ones — otherwise duplicates corrupt the collapsed .toe
            sed -i '/wine_ui_fixes/d' "$TOC_PATH" 2>/dev/null || true
            for entry in "${{FIX_ENTRIES[@]}}"; do
                echo "$entry" >> "$TOC_PATH"
            done
            WINEPREFIX="$WINE_PREFIX" "$WINE64_BIN" "$TOE_COLLAPSE" "$WINE_TOE" >/dev/null 2>&1 || true
        else
            # Surface patch failures instead of staying silent (broken fonts
            # with no trace)
            notify_warn "font fix: failed to expand $TOE_PATH (text may not render)"
        fi
        rm -rf "$DIR_PATH" "$TOC_PATH" 2>/dev/null || true
    fi
}}

if [ -z "$NO_PATCH" ] && [ -f "$TOE_EXPAND" ] && [ -f "$TOE_COLLAPSE" ] && [ -f "$FIX_FILE" ]; then
    FIX_TMPDIR="$(mktemp -d "/tmp/td_fix_launcher.XXXXXX" 2>/dev/null || true)"
    if [ -n "$FIX_TMPDIR" ]; then
        FIX_COPY="$FIX_TMPDIR/fix.tox"
        cp -f "$FIX_FILE" "$FIX_COPY" 2>/dev/null || true
        WINE_FIX_COPY="z:${{FIX_COPY//\\/\\\\\\\\}}"
        WINEPREFIX="$WINE_PREFIX" "$WINE64_BIN" "$TOE_EXPAND" "$WINE_FIX_COPY" >/dev/null 2>&1 || true

        if [ -d "$FIX_COPY.dir" ]; then
            FIX_ENTRIES=()
            while IFS= read -r entry; do
                [ -z "$entry" ] && continue
                [[ "$entry" == \\#* ]] && continue
                [ "$entry" = ".build" ] && continue
                FIX_ENTRIES+=("$entry")
            done < "$FIX_COPY.toc"

            FIX_FP=""
            if [ -d "$FIX_COPY.dir/wine_ui_fixes" ]; then
                FIX_FP="$(fp_tree "$FIX_COPY.dir/wine_ui_fixes")"
            fi

            while IFS= read -r -d '' NP_TOE; do
                check_and_patch_toe "$NP_TOE"
            done < <(find "$WINE_PREFIX/drive_c" -type f -iname 'NewProject.toe' -print0 2>/dev/null || true)

            PREF_FILE="$WINE_PREFIX/drive_c/users/steamuser/AppData/Local/Derivative/TouchDesigner099/pref.txt"
            if [ -f "$PREF_FILE" ]; then
                STARTUP_MODE=$(grep -E '^general\\.startupfilemode' "$PREF_FILE" 2>/dev/null | head -n1 | cut -f2 | tr -d '\\r' || true)
                if [ "$STARTUP_MODE" = "2" ]; then
                    CUSTOM_TOE=$(grep -E '^general\\.startupfilename' "$PREF_FILE" 2>/dev/null | head -n1 | cut -f2- | tr -d '\\r' || true)
                    if [ -n "$CUSTOM_TOE" ]; then
                        PATCH_CUSTOM_TOE="${{CUSTOM_TOE#z:}}"
                        PATCH_CUSTOM_TOE="${{PATCH_CUSTOM_TOE#Z:}}"
                        PATCH_CUSTOM_TOE="${{PATCH_CUSTOM_TOE//\\\\\\\\//}}"
                        [ -f "$PATCH_CUSTOM_TOE" ] && check_and_patch_toe "$PATCH_CUSTOM_TOE"
                    fi
                fi
            fi

            if [ -n "$INPUT_PATH" ] && [[ "$INPUT_PATH" == *.toe ]]; then
                check_and_patch_toe "$INPUT_PATH"
            fi
        fi
        rm -rf "$FIX_TMPDIR" 2>/dev/null || true
    fi
fi

# --- First-launch setup: wineboot, license, DPI ---
INIT_FLAG="$WINE_PREFIX/.td_initialized"

if [ ! -f "$INIT_FLAG" ] && [ -f "$WINE_BIN/wineboot" ]; then
echo "TouchDesigner - Setting up..."

if [ -d "$WINE_PREFIX/drive_c/ProgramData/Derivative" ]; then
    rm -rf "$WINE_PREFIX/drive_c/ProgramData/Derivative.bak" 2>/dev/null || true
    cp -r "$WINE_PREFIX/drive_c/ProgramData/Derivative" \
          "$WINE_PREFIX/drive_c/ProgramData/Derivative.bak" 2>/dev/null || true
fi

WINEPREFIX="$WINE_PREFIX" "$WINE_BIN/wineboot" -u >/dev/null 2>&1 || true
sleep 2

if [ -d "$WINE_PREFIX/drive_c/ProgramData/Derivative.bak" ]; then
    rm -rf "$WINE_PREFIX/drive_c/ProgramData/Derivative" 2>/dev/null || true
    cp -r "$WINE_PREFIX/drive_c/ProgramData/Derivative.bak" \
          "$WINE_PREFIX/drive_c/ProgramData/Derivative" 2>/dev/null || true
    rm -rf "$WINE_PREFIX/drive_c/ProgramData/Derivative.bak" 2>/dev/null || true
fi

XFT_DPI=$(xrdb -query 2>/dev/null | grep "^Xft.dpi" | awk '{{print $2}}' | head -1)
if [ -z "$XFT_DPI" ]; then
    XFT_DPI=$(xdpyinfo 2>/dev/null | grep "resolution" | grep -oP '[0-9]+(?=x)' | head -1)
fi
XFT_DPI=${{XFT_DPI:-96}}

if [ "$XFT_DPI" -lt 108 ]; then
    LOGPX=96
elif [ "$XFT_DPI" -lt 132 ]; then
    LOGPX=120
elif [ "$XFT_DPI" -lt 168 ]; then
    LOGPX=144
else
    LOGPX=192
fi

WINEPREFIX="$WINE_PREFIX" "$WINE64_BIN" reg add \
    "HKEY_CURRENT_CONFIG\\\\Software\\\\Fonts" \
    /v LogPixels /t REG_DWORD /d $LOGPX /f >/dev/null 2>&1 || true

touch "$INIT_FLAG"
elif [ -n "${{TD_DPI:-}}" ]; then
WINEPREFIX="$WINE_PREFIX" "$WINE64_BIN" reg add \
    "HKEY_CURRENT_CONFIG\\\\Software\\\\Fonts" \
    /v LogPixels /t REG_DWORD /d "${{TD_DPI}}" /f >/dev/null 2>&1 || true
fi

# Auto-cleanup backups older than 30 days
if [ -d "$BACKUP_DIR" ]; then
    find "$BACKUP_DIR" -name '*.bak' -type f -mtime +30 -delete 2>/dev/null || true
fi

# --- CodeMeter runtime (dongles / network-shared licenses) ---
# Windows services do not auto-start under Wine. If the CodeMeter runtime
# was installed into the prefix (TD installer's "Install Runtime for Dongle
# Licensing" option), start it so TouchDesigner can reach dongle and
# network-shared licenses. Best-effort: TD still launches without it.
CODEMETER_EXE="$WINE_PREFIX/drive_c/Program Files (x86)/CodeMeter/Runtime/bin/CodeMeter.exe"
[ -f "$CODEMETER_EXE" ] || CODEMETER_EXE="$WINE_PREFIX/drive_c/Program Files/CodeMeter/Runtime/bin/CodeMeter.exe"
if [ -f "$CODEMETER_EXE" ] && ! pgrep -x 'CodeMeter.exe' >/dev/null 2>&1; then
    log "Starting CodeMeter runtime..."
    WINEPREFIX="$WINE_PREFIX" "$WINE64_BIN" "$CODEMETER_EXE" >/dev/null 2>&1 &
    for _ in 1 2 3 4 5 6 7 8; do
        pgrep -x 'CodeMeter.exe' >/dev/null 2>&1 && break
        sleep 0.5
    done
fi

# Launch
log "Launching $TOUCHDESIGNER_EXE ${{EXTRA_ARGS[*]}}"
PATH="$WINE_BIN:$PATH"
export WINEPREFIX="$WINE_PREFIX"
exec "$WINE64_BIN" "$TOUCHDESIGNER_EXE" "${{EXTRA_ARGS[@]}}"
'''

    with open(LAUNCHER_PATH, "w") as f:
        f.write(launcher_content)

    os.chmod(LAUNCHER_PATH, 0o755)
    success(f"Launcher created: {LAUNCHER_PATH}")

    # ── `touchdesigner` terminal command (symlink) ──
    # The launcher is symlink-safe: nothing depends on $0 beyond the
    # container re-exec (the symlink path exists in the shared home too).
    # Never clobber a file that is not our own symlink.
    if os.path.lexists(TD_COMMAND) and os.path.realpath(TD_COMMAND) != LAUNCHER_PATH:
        warning(f"Not overwriting {TD_COMMAND} (exists and is not our launcher)")
    else:
        try:
            if os.path.lexists(TD_COMMAND):
                os.remove(TD_COMMAND)
            os.symlink(LAUNCHER_PATH, TD_COMMAND)
            success(f"Command created: {TD_COMMAND}")
        except OSError as e:
            warning(f"Could not create {TD_COMMAND}: {e}")

    return LAUNCHER_PATH
