"""Launcher script generation."""

import os

from .utils import TD_BASE_DIR, ensure_dir, success
from .wine import RUNNER_DIR, WINE_PREFIX

LAUNCHER_PATH = os.path.expanduser("~/.local/bin/launch-touchdesigner.sh")


def create_launcher_script(nvidia_offload: bool = False) -> str:
    """Generate the launcher shell script and return its path."""
    ensure_dir(os.path.dirname(LAUNCHER_PATH))

    nvidia_mode = "Y" if nvidia_offload else "N"

    launcher_content = f'''#!/bin/bash
# TouchDesigner launcher — generated by td-install
TD_BASE_DIR="${{TD_BASE_DIR:-${{HOME}}/.local/share/touchdesigner-linux}}"
RUNNER_DIR="${{TD_BASE_DIR%/}}/runner"
WINE_PREFIX="${{TD_BASE_DIR%/}}/prefix"
USE_NVIDIA_DGPU="{nvidia_mode}"

export WAYLAND_DISPLAY=""
export __GL_YIELD="USLEEP"

find_touchdesigner_exe() {{
    find "$WINE_PREFIX/drive_c" -type f -iname 'TouchDesigner.exe' 2>/dev/null | sort -V | tail -n 1
}}

TOUCHDESIGNER_EXE_OVERRIDE_ARG=""
if [[ "$1" == "--exe" ]] && [ -n "$2" ]]; then
    TOUCHDESIGNER_EXE_OVERRIDE_ARG="$2"
    shift 2
elif [[ "$1" == --exe=* ]]; then
    TOUCHDESIGNER_EXE_OVERRIDE_ARG="${{1#--exe=}}"
    shift
fi

if [ -n "$TOUCHDESIGNER_EXE_OVERRIDE_ARG" ] && [ -f "$TOUCHDESIGNER_EXE_OVERRIDE_ARG" ]; then
    TOUCHDESIGNER_EXE="$TOUCHDESIGNER_EXE_OVERRIDE_ARG"
elif [ -n "$TOUCHDESIGNER_EXE_OVERRIDE" ] && [ -f "$TOUCHDESIGNER_EXE_OVERRIDE" ]; then
    TOUCHDESIGNER_EXE="$TOUCHDESIGNER_EXE_OVERRIDE"
else
    TOUCHDESIGNER_EXE="$(find_touchdesigner_exe)"
fi

if [ -z "$TOUCHDESIGNER_EXE" ]; then
    echo "Error: TouchDesigner.exe not found in Wine prefix."
    exit 1
fi

if command -v nvidia-smi >/dev/null 2>&1; then
    if [ "$USE_NVIDIA_DGPU" = "Y" ] || [ "$USE_NVIDIA_DGPU" = "y" ]; then
        export __NV_PRIME_RENDER_OFFLOAD=1
        export __GLX_VENDOR_LIBRARY_NAME=nvidia
        export __VK_LAYER_NV_optimus=NVIDIA_only
        export DRI_PRIME=1
    fi
fi

EXTRA_ARGS=()
if [ -n "$1" ]; then
    INPUT_PATH="$1"
    if [[ "$INPUT_PATH" == file://* ]]; then
        INPUT_PATH="${{INPUT_PATH#file://}}"
        INPUT_PATH="$(python3 -c "import sys, urllib.parse; print(urllib.parse.unquote(sys.argv[1]))" "$INPUT_PATH" 2>/dev/null || echo "$INPUT_PATH")"
    fi
    WINE_PATH="z:${{INPUT_PATH//\\/\\\\\\\\}}"
    EXTRA_ARGS=("$WINE_PATH")
fi

PATH="$RUNNER_DIR/bin:$PATH"
export WINEPREFIX="$WINE_PREFIX"
exec "$RUNNER_DIR/bin/wine64" "$TOUCHDESIGNER_EXE" "${{EXTRA_ARGS[@]}}"
'''

    with open(LAUNCHER_PATH, "w") as f:
        f.write(launcher_content)

    os.chmod(LAUNCHER_PATH, 0o755)
    success(f"Launcher created: {LAUNCHER_PATH}")
    return LAUNCHER_PATH
